### ISSUE TITLE
can we use with CSP Program ?

### ISSUE THREAD

**Issue by dumins** [PartnerCenterSamples/Reseller-Web-Application#10]
can we use with CSP Program ?

**Comment by RaedJarrar** [comment]
Of course! This is the main purpose of this web store front portal. You can deploy it from Partner Center by navigating to account settings -> web storefront. This will deploy the code from this repository. You can also follow the readme.md file and run it locally and deploy it yourself if you wanted.

**Comment by dumins** [comment]
when i download the code and run from visual studio there are lots of erros .
Ex: Error	2	Invalid token ';' in class, struct, or interface member declaration	C:\Users\Admin\Documents\GitHub\Reseller-Web-Application\Source\PartnerCenter.CustomerPortal\BusinessLogic\Exceptions\PartnerDomainException.cs	61	81	PartnerCenter.CustomerPortal

**Comment by dumins** [comment]
i think you guys used C# 6.0 So I need to install VS 2015 and open and it didnt compile with VS 2013

**Comment by RaedJarrar** [comment]
Please let us know if things are fine so that we close this issue.

**Comment by tameemansari** [comment]
@dumins . Please confirm else we will close this issue in a few days. Thanks.
