### ISSUE TITLE
International Usage

### ISSUE THREAD

**Issue by ankbs** [PartnerCenterSamples/Reseller-Web-Application#11]
Hallo,
many thanks for your work.
But for an European / German CSP we need an other configuration:
Please fix or describe an "How-To" (for IT-pro and not DEV :-) )
- At the customer registration page, please change the phone number format into an international or describe how (and where) we can change that into european (or german) format
- PayPal order dosn't work with german PayPal Business Accounts, because CC isn't allow. We need like PayPal Express Checkout. I don't know, if the CC restriction is only in Germany or in Europe, too.
- Customer Registration page, please add or read from the partnercenter all allowed countries. as an EFTA / EU CSP we can sell into more as one country. 

Thanks for your support
Michael

**Comment by tameemansari** [comment]
We are looking into supporting countries beyond US. This will also include supporting PayPal express checkout support (and PayPal accounts as a funding instrument along side credit cards (where applicable)).

**Comment by tameemansari** [comment]
Closing this issue since the release is now out.
