### ISSUE TITLE
Customer unable to login

### ISSUE THREAD

**Issue by Sodininkas** [PartnerCenterSamples/Reseller-Web-Application#12]
Hi,

I created web app from https://github.com/PartnerCenterSamples/Reseller-Web-Application. Now only partners can login to the app with admin rolw, but when i try login to the site with newly created customer user it promt's error - "access_denied" with response - "The application needs access to a service that your organization has not subscribed to. Please contact your Administrator to review the configuration
 of your service subscriptions." What, i'm missing?

Thanks

**Comment by RaedJarrar** [comment]
Looks like you manually deployed the application. Did you make sure you used an AD web application and set it to multi-tenant?

**Comment by Sodininkas** [comment]
Thanks for reply,

Yes i manually deployed it. I just tried deploy from external source github and it succesfully worked, the customer after login promts that he agree with credential usage and logs on(before i dont have that promt). I don' get it what i'm missing  whit manually deploy, i set to multitenant ad web app. I also leave in web config partnerCenterApplicationId and webPortalClientId same.

**Comment by Sodininkas** [comment]
It worked! thanks god. It was with webPortalClientId, this had to be different, i copy id and secret from working external deployment(helped me a lot whit this), i don't know from it get those. and webPortalClientId guid's from created application in microsoft csp portal. And everything is in good shape now.

Thanks

**Comment by RaedJarrar** [comment]
Wonderful! Glad it all worked out.

**Comment by LloydApter** [comment]
Hi, 

Which is the correct value for the ''webPortalClientId'' ?

Thanks
