### ISSUE TITLE
How about Azure Subscriptions ?

### ISSUE THREAD

**Issue by dumins** [PartnerCenterSamples/Reseller-Web-Application#17]
How about Azure Subscriptions ?

**Comment by tameemansari** [comment]
@dumins. This is on our roadmap for the web storefront. Please share your thoughts on what you would like to see about supporting Azure Subscriptions. Will it be sufficient to just list out the subscriptions or would you like to see more. Thanks.

**Comment by dumins** [comment]
Azure Subscriptions are Usage Based. We need to show the Usage of particular month to the client.
