### ISSUE TITLE
Removing Paypal Option

### ISSUE THREAD

**Issue by dumins** [PartnerCenterSamples/Reseller-Web-Application#18]
Is it possible to remove the Paypal option for the configuration level. ?

**Comment by tameemansari** [comment]
Can you help me understand your question better? Do you mean replace the payment gateway? or removing some option in the PayPal gateway.

**Comment by dumins** [comment]
Need to Remove the Paypal option because we dont have support for Paypal here.

**Comment by tameemansari** [comment]
Thanks for clarifying. Which country is this and is there an alternative Payment gateway which you intend to implement?

**Comment by dumins** [comment]
Sri Lanka . I'm actually observing the application and Is there any Admin Panel to view all the orders ?

**Comment by tameemansari** [comment]
A customer can view all their purchases / transactions after they login in the "My Subscriptions" page. 
The admin pages do not currently have a feature to view all the orders/transactions made by various customers in the portal. A partner can always view these orders in Partner Center. Is this something which is critical for you. If you can list out all your needs we can add to our backlog and see how we can prioritize. Thanks.

**Comment by tameemansari** [comment]
@dumins. I would appreciate if you can try [this release which just got out](https://github.com/PartnerCenterSamples/Reseller-Web-Application/releases/tag/v1.2).

**Comment by dumins** [comment]
Thanks Tameen
