### ISSUE TITLE
Urgent: After deploying, no Startsite is showing

### ISSUE THREAD

**Issue by ankbs** [PartnerCenterSamples/Reseller-Web-Application#28]
Hi,
many thanks for your new build. The feature list Looks like very good.

But, when i deploy the solution over the partnercenter, there is no startsite showing. i can see Only the text inside the TAB (with Edge and IE on Windows 10)
The same is, when i deploy it Manual inside the current and running azurewebsite configuration.

Thanks again for oyur great Support.
Michael

**Comment by tameemansari** [comment]
Can you give me a link to the deployed site.

**Comment by ankbs** [comment]
https://partnercentercustomerportal20170113114928.azurewebsites.net/
is the last deployment

**Comment by ankbs** [comment]
and this is deployed one Minute ago from partnercenter
https://hcloudo365webshop.azurewebsites.net/

**Comment by ankbs** [comment]
I try look with F12 :-)
is this helping?
 Strings: {
            /*
                Framework strings
            */
            CurrentLocale: "de-DE",
            Loading: "Laden",
          ......
            Delete: "Löschen",
            Save: "Speichern",
            Undo: ""Rückgängig"",
ERROR --> Expected '}'
            NotificationsSummary: " neue Benachrichtigungen",

**Comment by tameemansari** [comment]
Can we follow up on this over email. Please drop me a note on tansar at Microsoft.com

**Comment by ankbs** [comment]
Hi,
i want to share the solution.
Inside the ressource file for german language, search for Undo: ""Rückgängig"" and delete the double " so there is only one like "Rückgängig".
This solved the error.

Regards
Michael

**Comment by tameemansari** [comment]
Thank you @ankbs. I will PR your changes after reviewing them by end of day today.

**Comment by tameemansari** [comment]
Just completed a PR and handled this issue for all the supported non English languages.
