### ISSUE TITLE
Getting subscription name after registration

### ISSUE THREAD

**Issue by Bikram0** [PartnerCenterSamples/Reseller-Web-Application#37]
Hi, I am having a problem on getting the subscription name or the product name after registering. After buying the certain product, i need to show on the registration confirmation page. Would someone please help me to get the subscription name
![error](https://cloud.githubusercontent.com/assets/18627032/24545884/c7f21220-1628-11e7-8b0c-ccbbefa58226.PNG)

**Comment by tameemansari** [comment]
Are you working on a private fork? I don't think we can display the subscription on this page in the current implementation since the order hasn't been placed at this point. Can you share additional details of your scenario.

**Comment by Bikram0** [comment]
I was trying to retrieve the product information after the customer clicks on buy now button. The product information should be displayed in Customer Registration Confirmation page. I have added the model view in its respective script file. But it shows [object object] while trying to retrieve product name information. 

I was trying to show this information as it will be easier about what the customer has bought in the CSP Portal. So, subscription could be added later on.

**Comment by tameemansari** [comment]
Sorry @Bikram0 I am still not clear about this statement. 

> I was trying to show this information as it will be easier about what the customer has bought in the CSP Portal. So, subscription could be added later on.

If you have a fork somewhere on GitHub please point me to these changes and I can suggest next steps / fixes accordingly. Hope this helps.

**Comment by tameemansari** [comment]
You can always harvest the items for which the order will be generated from the [SubscriptionsToOrder property of the viewModel](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/RegistrationConfirmationPresenter.js#L17). You will need to write the view to render these pieces of the viewModel in the [Registration confirmation view page](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Views/Shared/RegistrationConfirmation.cshtml). After the order is processed successfully the subsequent page already displays the list of subscriptions purchased. 

The storefront admin cannot view the purchases done by customers in the portal but they can always view them in Partner Center. The storefront is primarily focused on providing and enhancing the partner's end customer experience. 

I can support you adding the second scenario on a private fork of this codebase and we can evaluate bringing it into the core source. Hope you would understand.

**Comment by Bikram0** [comment]
Thanks for the guidance sir. I have done all the process according to your guidelines. But still, the products that has been ordered by the customers isn’t displayed in RegistrationConfirmation view page. I have added the viewModel in its respective script file and the view page. But still it doesn’t show its respective data. I have attached the file that I am trying to display in the red rectangle.
![image](https://cloud.githubusercontent.com/assets/18627032/24847463/c8f607f2-1de0-11e7-9b6e-3b503749bc30.png)

**Comment by tameemansari** [comment]
I am sorry @Bikram0 I am not sure I can help without understanding what you are trying to do. The screenshot you have attached is misleading to me. Is the screenshot your desired end goal / expectation or is your current implementation? 

This page in our implementation doesn't place the order for the subscription. It only has generated the customer and associated it to the partner. The subscription order is placed after the payment experience pages. 

I am open to a call or some other means in which we can discuss your issue and hopefully I can advise accordingly.
