### ISSUE TITLE
custom domain with custom SSL login error

### ISSUE THREAD

**Issue by ankbs** [PartnerCenterSamples/Reseller-Web-Application#38]
Hello,
after we configure our custom domain / URL and attach a certificate, we have following error when the user is using the custom domain:
"IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'."

When the same user using the app URL, it's working.
I have configure all "answer" URLs in the AAD application.
http:// - https://business.hcloud.services
the app URL is http:// - https://hcloudshop.azurewebsites.net

Thanks for your support
Regards
Michael

**Comment by ankbs** [comment]
Hello....
Is there someone to hel for that issue?
Thank you
Michael

**Comment by tameemansari** [comment]
@ankbs Will revert back in a few days.

**Comment by tameemansari** [comment]
@ankbs Has the issue been fixed. I tried to login to your site and didn't see any issues.
