### ISSUE TITLE
Default paypal timeout inappropriate

### ISSUE THREAD

**Issue by lochiiconnectivity** [PartnerCenterSamples/Reseller-Web-Application#4]
The default HTTP timeout in the [Paypal NET SDK](https://github.com/paypal/PayPal-NET-SDK) is 30 seconds [(source)](https://github.com/paypal/PayPal-NET-SDK/blob/77b14e19402e7ee8dfa170cbce98d4b14c8ee6b5/Source/SDK/Manager/ConfigManager.cs#L26)

This is inappropriate when using the paypal developer sandbox, which takes longer to respond.

Will submit a pull to fix.

**Comment by RaedJarrar** [comment]
We are in the process of revamping the PayPal integration code. We will take this change in however since it is minor.
