### ISSUE TITLE
Error when opening with VS2017

### ISSUE THREAD

**Issue by patrickyong** [PartnerCenterSamples/Reseller-Web-Application#40]
I have the following error but as far as I know VS2017 comes with Azure SDK for .NET, what's missing here?

 Source\CustomerPortal.Deployment\CustomerPortal.Deployment.deployproj: The application which this project type is based on was not found. Please try this link for further information: https://go.microsoft.com/fwlink/?LinkId=660342&projecttype=151D2E53-A2C4-4D7D-83FE-D05416EBD58E

**Comment by patrickyong** [comment]
Looks like I got the same error message if I open it with VS2013 as well. I don't have a VS2015 installation at the moment.

**Comment by tameemansari** [comment]
The code doesn't support VS2013. VS2015 should work just fine. For VS2017 we found that installing Azure SDK 2.9 resolves the issue you are reporting. You can download it from https://www.microsoft.com/en-us/download/details.aspx?id=51657 

please confirm then I will close this issue.
