### ISSUE TITLE
Redirecting after login

### ISSUE THREAD

**Issue by rodmcleay** [PartnerCenterSamples/Reseller-Web-Application#45]
Hi,

I have the Customer Portal sample project setup and running in Visual Studio 2017.
Its deployed to Azure and running there, as is, out of the box.

My issue is debugging locally.
Only after I log in, it redirects to the azure hosted site instead of my https://localhost:44360 which should be the referrer.

I can't see any ref in the code to the  deployed site url I can't really debug whilst its redirecting to the deployed site (from the MS login page).

I've not seen any articles or issues like this being raised by others, So I'm sure I'm missing something quite simple. But I can't see it.

Many thanks for your time,
Rod

**Comment by spappuru** [comment]
Could you please add the second 'Reply URL' parameter value as https://localhost:44360 for the App registered in Azure AAD and then verify?
Path: Login to Azure Portal --> Active Directory --> App registrations --> Select the App that you have configured --> Go to Reply URL's and add the new URL for localhost.
