### ISSUE TITLE
Subscription Add-Ons

### ISSUE THREAD

**Issue by ingramleedy** [PartnerCenterSamples/Reseller-Web-Application#46]
Has anyone figure a way to handle "Add-on"s?

For example, if you add E1 plan, you also want to add Advance Threat Protection at the same time or the ability to change add-ons?

**Comment by tameemansari** [comment]
Marked as an enhancement. The storefront currently doesn't support add-ons if there is enough demand we can look at bringing this for a future release of the storefront.
