### ISSUE TITLE
Can't login with Client Credentials

### ISSUE THREAD

**Issue by allanzh** [PartnerCenterSamples/Reseller-Web-Application#50]
I'm trying to access the portal using client credentials and this error occurs :
![screenshot_5](https://user-images.githubusercontent.com/2539476/30063713-f4c50d9c-9225-11e7-9d1c-3c546997abf1.png)

**Comment by ParagMJoshi** [comment]
I was able to use the Client Credentials and login, just now.
Can you verify that the provided Credentials are correct. 
Parag.

**Comment by allanzh** [comment]
Thanks @ParagMJoshi 
In contact with @isaiahwilliams via e-mail he gives me some tips to understand and solve this issue.
I'll detail here for help people who have the same problem.
The error occurs because application by default comes with no support for multi tenant use. So I follow this steps:

- login in Azure Portal > Azure Active Directory > App Registrations, then select the corresponding application
![gh1](https://user-images.githubusercontent.com/2539476/30211525-bd62b47c-9477-11e7-8e73-0ef457b09fd3.png)

- in Properties click Yes to Multi-tenanted
![gh2](https://user-images.githubusercontent.com/2539476/30211524-bd61e86c-9477-11e7-9cef-7255e230f8b1.png)
