### ISSUE TITLE
Unexpected behaviors in portal

### ISSUE THREAD

**Issue by allanzh** [PartnerCenterSamples/Reseller-Web-Application#53]
Hello guys,

I'm facing a problem when I try to buy one subscription without loggin.

I configured storefront to pre-approve transactions for all, but when I pick an offer and put all informations required to create a new customer, it redirects me to PayPal gateway. 
So I try to run using localhost to follow unexpected redirection and fix it, but I click in "Proceed to Payment" button and throws me this following exception:
_0x800a138f - JavaScript runtime error: Unable to get property 'type' of undefined or null reference_
![screenshot_4](https://user-images.githubusercontent.com/2539476/30542701-bb80a8da-9c56-11e7-8a0c-b1b08064bff8.png)

So, portal is having different behaviors when is running on azure or localhost.

**Comment by tameemansari** [comment]
This is by design. You can only preapprove existing customers. Customers who are being created need to go through the payment gateway experience.

**Comment by allanzh** [comment]
thanks for replying @tameemansari .
 I think I misunderstood the following message that is in "pre-approve" page: _“Select all” will mark all current and future customers as pre-approved to transact in the store front._
So, just to be clear, all newer customers need to pass first in paypal gateway? because in my scenario I need to bypass this step.

**Comment by tameemansari** [comment]
Unfortunately we don't think its ideal to enable a new customer to be preapproved since the customer partner relationship is not yet established. You can feel free to fork the code and incorporate this behavior.
