### ISSUE TITLE
Cross origin issue

### ISSUE THREAD

**Issue by jamesoneill** [PartnerCenterSamples/Reseller-Web-Application#55]
Hi, We are trying to deploy your re-seller portal in azure manually as we will be adding our own payment provider eventually. 

I have followed the instructions apart from the website is hosted under a different subscription to the Active directory in azure. Not sure if this is the problem but thought i should mention it up front.

The website loads and i can see the loading image but it hangs. if i check in the developer console we are getting this error:
`XMLHttpRequest cannot load https://login.microsoftonline.com/common/oauth2/authorize?client_id=f4e43cb9-258f-4d6d-ae43-ed9357bab384&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dRbidEH3rZ_JhIw-5KXci3tIBv1h9_coYLfuHd6HiNFw5ETbtijku8XDztTD74Sm76KuhDyvNP4MoLATeHTBK0M_ztZM_CA27-Y4psxREa-Qpcg3L9kZUqBYJUJosdpfMGPDgrN8q78XPiqtbM8u64-VD3fXI8p4tpD2fssyGjRU&nonce=636420202582326337.ZmVkY2JkYWQtNmRhNy00ZDg5LTllNTUtMjY3NGVhMzBiOTU1ZTM1NTY5ZWYtMjc4MS00ZTc2LTgxNmMtNzM1NzAxNzg0NTM2&lc=2057&x-client-SKU=ID_NET&x-client-ver=1.0.40306.1554. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dccspstorefront.azurewebsites.net' is therefore not allowed access.`

**Comment by ParagMJoshi** [comment]
Hello Jamesoneill,

I think this is related to the fact that it is under different subscription. I did check the link https://dccspstorefront.azurewebsites.net, I can see the Issue you mentioned and the error you mentioned. 

However I am not able to debug this issue as I cannot repro the issue in my environment. 
If you can send me the Web.config in mail at v-paragj@microsoft.com I can help you.

Thanks
Parag.

**Comment by ParagMJoshi** [comment]
Hello Jamesoneill

We have not heard back from you. If this is still a issue Please reply back on mail and I can help you debug this issue other wise We would be closing this issue tomorrow.
thanks
Parag.

**Comment by jamesoneill** [comment]
Well we used the partner centre deploy-er which through some errors but actually provisioned in the end. Instead of provisioning it all our selves as we had run into this issue. 

We have decided to roll our own solution to the problem as it doesn't quite fit our business needs. The developer in me would like to understand what the issue was, if you would like to go through the motions to fix a non issue that could be an issue for others.

It wasn't just two different subscriptions it was two completely different tenants which i believe is slightly different?

Here is the web.config you requested: 

`
<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    
    <add key="aadEndpoint" value="https://login.microsoftonline.com/" />
    
    <add key="aadGraphEndpoint" value="https://graph.windows.net" />
    
    <add key="partnerCenter.applicationId" value="78306c79-7025-45d6-bb56-fd8577c937ee" />
    
    <add key="partnerCenter.applicationSecret" value="" />
    
    <add key="partnerCenter.AadTenantId" value="1cf852bb-fbe3-48e1-ab2a-83d8a5e28524" />
    
    <add key="partnerCenter.apiEndPoint" value="https://api.partnercenter.microsoft.com" />
    
    <add key="webPortal.clientId" value="78306c79-7025-45d6-bb56-fd8577c937ee" />
    
    <add key="webPortal.clientSecret" value="" />
    
    <add key="webPortal.AadTenantId" value="1cf852bb-fbe3-48e1-ab2a-83d8a5e28524" />
    
    <add key="webPortal.configurationPath" value="Configuration\WebPortalConfiguration.json" />
    
    <add key="webPortal.azureStorageConnectionString" value="UseDevelopmentStorage=true" />
    
    <add key="webPortal.cacheConnectionString" value="" />
    
    <add key="webPortal.azureStorageConnectionEndpointSuffix" value="core.windows.net" />
  </appSettings>
  
  <system.web>
    <authentication mode="None" />
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5" />
    <customErrors mode="Off"></customErrors>
    <httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
    </httpModules>
  </system.web>
  <system.webServer>
    <modules>
      <remove name="FormsAuthentication" />
      <remove name="ApplicationInsightsWebTracking" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
    </modules>

    <rewrite>
      <rules>
        <rule name="Force HTTPS" enabled="true">
          <match url="(.*)" ignoreCase="false" />
          <conditions>
            <add input="{HTTPS}" pattern="off" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}/{R:1}" appendQueryString="true" redirectType="Permanent" />
        </rule>
      </rules>
    </rewrite>
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
    <validation validateIntegratedModeConfiguration="false" />
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.OAuth" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.Cookies" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.40306.1554" newVersion="4.0.40306.1554" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocol.Extensions" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.40306.1554" newVersion="1.0.40306.1554" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.1.0" newVersion="5.8.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.1.0" newVersion="5.8.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.8.1.0" newVersion="5.8.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Antlr3.Runtime" publicKeyToken="eb42632606e9261f" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.2" newVersion="3.5.0.2" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.KeyVault.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.13.9.1126" newVersion="3.13.9.1126" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.AI.Agent.Intercept" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.7.0" newVersion="2.0.7.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
</configuration>
`

What further information would you need from me to work out what has happend?

**Comment by isaiahwilliams** [comment]
I am going to close this issue, since we have updated the code a number of times since this issue was opened. If the issue still presists please feel free to reopen this issue or create a new one.
