### ISSUE TITLE
Error aquiring new subscriptions with new Customer.

### ISSUE THREAD

**Issue by allanzh** [PartnerCenterSamples/Reseller-Web-Application#56]
Hi everyone,
I'm facing an error when I try to buy a subscription without logging into portal.
I've follow this steps:

1. Access Portal.
2. Select the first Offer.
3. Click "buy now" button.
4. Put all information needed.
5. Click "Proceed to Payment" button.
6. Make the payment using PayPal.

When PayPal redirects me back to Portal I see the screen below.

![screenshot_9](https://user-images.githubusercontent.com/2539476/30859599-c76f631c-a29a-11e7-9d54-4b250f8891f3.png)

But When I check my Customer List in Partner Center Sandbox, the Customer was created with the same info that I put on form and no subscription assigned.

**Comment by tameemansari** [comment]
Closing the issue since you may have resolved this already.
