### ISSUE TITLE
How could get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Centner

### ISSUE THREAD

**Issue by abdelgrib** [PartnerCenterSamples/Reseller-Web-Application#57]
The API of Microsoft Store Partner Center using RateCards returns usage-based services (Azure Services) and can't get license-based services pricing ? I could download the Excel file but my question is , is there any way to get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Center ?

When getting offers using the API, some information are missing like : ERP Price, List Price, Valid-To Date, Valid-From Date ?

**Comment by tameemansari** [comment]
Sorry there is no API to get these details. You would have to rely on the excel sheet downloadable from Partner Center web site.
