### ISSUE TITLE
How can I upload my local files to partner server request?

### ISSUE THREAD

**Issue by AnandKumar2610** [PartnerCenterSamples/Reseller-Web-Application#58]
Sample code: https://msdn.microsoft.com/en-us/library/partnercenter/mt805812.aspx

**Comment by isaiahwilliams** [comment]
Hi AnandKumar2610, the storefront does not provide the ability to manage support requests. This portal is designed for customers to purchase, and manage, subscriptions from a Cloud Solution Provider partner. Are you looking for a solution to help support your customers? Or are you suggesting that this functionality be added to the storefront?

**Comment by isaiahwilliams** [comment]
Currently this feature is not on the roadmap for new functionality to be added. Considering this I am going to close this issue. Please feel free to reopen it if you have any quesitons.
