### ISSUE TITLE
How to get Notes from Service Requests?

### ISSUE THREAD

**Issue by AnandKumar2610** [PartnerCenterSamples/Reseller-Web-Application#63]
My Code:
`ResourceCollection<ServiceRequest> serviceRequests = partnerOperations.ServiceRequests.Get();`
I got only NULL values for Notes!

Source: https://docs.microsoft.com/en-us/partner-center/develop/get-all-service-requests-for-a-customer

Thanks in advance
-Anand

**Comment by isaiahwilliams** [comment]
Hi Anand, 

I would recommend that you check out the [Service Request examples](https://github.com/PartnerCenterSamples/Partner-Center-SDK-Samples/tree/master/Source/Partner%20Center%20SDK%20Samples/ServiceRequests) from the Partner Center SDK sample project. If that does not help then it would be a good idea to open a support ticket through Partner Center regarding this question.

**Comment by AnandKumar2610** [comment]
Hi @isaiahwilliams  thank you for your reply.
Actually i am created 13 service request using SDK.

I got Notes if am using ID:
`ServiceRequest serviceRequestDetails = partnerOperations.ServiceRequests.ById(existingServiceRequest.Id).Get();`

When i use the below code to retrieve all service request notes, i am getting null value for all notes.
`ServiceRequest serviceRequestDetails = partnerOperations.ServiceRequests.Get();`

Source: https://docs.microsoft.com/en-us/partner-center/develop/get-service-request-details-by-id

Thanks in advance
-Anand

**Comment by isaiahwilliams** [comment]
Hi Anand, 

The behavior you described is excepted. You will notice that various components of the Partner Center API/SDK behave in this manner. This was done to ensure that the data being returned from the API is done so in an optimal manner. If you would like to get the notes for each service request then my recommendation would be 

1. Make the partnerOperations.ServiceRequests.Get() call to obtain a complete list of service requests
2. Iterate through the results from the above operation and request each service request by ID

What I have seen most partner do is use the partnerOperations.ServiceRequest.Get() function to obtain a list of service requests. Then they use that data to populate a website where the user can click on an issue to drill into it.

**Comment by isaiahwilliams** [comment]
Hi @AnandKumar2610, please let us know if you are still having issues. I am going to close this issue for now, but please feel free to reopen it.

**Comment by AnandKumar2610** [comment]
Hi @isaiahwilliams thanks for your reply.
I need one request and get all information's. Why i need loop and call each time. Suppose I have 500 Service Request mean it will hit server 500 times correct?
