### ISSUE TITLE
Authentication - One or more errors has occurred

### ISSUE THREAD

**Issue by isaiahwilliams** [PartnerCenterSamples/Reseller-Web-Application#64]
### Expected behavior
Upon successful authentication, using partner credentials, the configuration page be loaded. 

### Actual behavior
After successfully authenticating users are reporting they are receiving a generic error message that states, one or more errors has occurred. 

### Steps to reproduce the problem
Deploy the solution following the guidance provided at https://blogs.msdn.microsoft.com/iwilliams/2016/12/17/reseller-storefront/

**Comment by isaiahwilliams** [comment]
I have submitted PR #65 to provide a more meaningful error. This update will show the message from the inner exception instead of the generic "one or more errors has occurred." @tameemansari do you have any feedback?

**Comment by tameemansari** [comment]
Thanks @isaiahwilliams . Makes sense. I reviewed the PR and will approve shortly. There is a large PR coming in to support an additional payment gateway (for India). Feel free to take a look at that too.

**Comment by isaiahwilliams** [comment]
Thank you @tameemansari. I will be more than glad to take a look at the additional gateway PR. I am going to close this issue since you have completed the merge.
