### ISSUE TITLE
The reply address 'https://blablabla.azurewebsites.net/' does not match the reply address 'https://blablabla.azurewebsites.net' provided when requesting Authorization code. 

### ISSUE THREAD

**Issue by schuettecarsten** [PartnerCenterSamples/Reseller-Web-Application#73]
I get the following exception when CSP user tries to login:
`AADSTS70002: Error validating credentials. AADSTS50011: The reply address 'https://blablabla.azurewebsites.net/' does not match the reply address 'https://blablabla.azurewebsites.net' provided when requesting Authorization code.`

**Comment by isaiahwilliams** [comment]
Hi @schuettecarsten, you will need to update the reply address for the web portal Azure AD application in the Azure management portal to correct this issue. You can find more details on how this is done at https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication

**Comment by schuettecarsten** [comment]
Thank you.
