### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by MattHorvay** [PartnerCenterSamples/Reseller-Web-Application#79]
I tried deploying this from Partner Center yesterday.
It looks like the app service deployment is failing.

It says Reason: Merge pull request #78 from PartnerCenterSamples/dev-mca-update Added support for acceptance of the MCA

It got to "Running deployment command..." which failed.
The activity log for the deployment command is:

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
All packages listed in packages.config are already installed.
BusinessLogic\AzureStorageService.cs(108,100): error CS1003: Syntax error, ',' expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(29,17): error CS1043: { or ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(29,17): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(31,16): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(41,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(41,30): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(45,16): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\CoreSegment.cs(52,2): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(36,75): error CS1026: ) expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(36,97): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(36,97): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(68,14): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(73,73): error CS1026: ) expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(74,170): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(74,170): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(104,18): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(107,74): error CS1026: ) expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(107,125): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(107,125): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Filters\WebApi\ErrorHandlerAttribute.cs(114,22): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(35,17): error CS1043: { or ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(35,17): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(37,16): error CS1002: ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(47,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(47,28): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(52,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(52,27): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(52,28): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(52,41): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(52,43): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(57,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(57,27): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(57,28): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(57,41): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(57,43): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(62,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(62,31): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,16): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,26): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,27): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,33): error CS1519: Invalid token ',' in class, struct, or interface member declaration [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,42): error CS1519: Invalid token '>' in class, struct, or interface member declaration [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,58): error CS1519: Invalid token '{' in class, struct, or interface member declaration [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(67,63): error CS1519: Invalid token ';' in class, struct, or interface member declaration [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\Web Portal\WebPortalConfiguration.cs(114,1): error CS1022: Type or namespace definition, or end-of-file expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\ApplicationConfiguration.cs(96,17): error CS1043: { or ; expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\ApplicationConfiguration.cs(96,17): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\ApplicationConfiguration.cs(104,23): error CS1014: A get or set accessor expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Configuration\ApplicationConfiguration.cs(104,23): error CS1513: } expected [D:\home\site\repository\src\Storefront\Storefront.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\src\Storefront\Storefront.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d6350a4770f4a8";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\78.11002.3584\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by isaiahwilliams** [comment]
Hi @MattHorvay, 

Thank you for opening this issue. I have corrected this issue and you should now be able to deploy it without an issue. Please let me know if you have any issues.

**Comment by MattHorvay** [comment]
That fixed it.
Thank you!
