### ISSUE TITLE
CloudStorageAccount BlobStorage Uri Mismatch

### ISSUE THREAD

**Issue by emilkje** [PartnerCenterSamples/Reseller-Web-Application#8]
Trying to get the sample running locally with the Azure Storage Emulator and getting the following error on initial page load: 

`Primary and secondary location URIs in a StorageUri must point to the same resource.
Parameter name: secondaryUri`

This error is thrown at AzureStorageService.cs at line 91
```
Line 89:             if (CloudStorageAccount.TryParse(azureStorageConnectionString, out cloudStorageAccount))
Line 90:             {
Line 91:                 this.storageAccount = new CloudStorageAccount(cloudStorageAccount.Credentials, endpointSuffix: azureStorageConnectionEndpointSuffix, useHttps: true);
Line 92:             }
Line 93:             else
```

azureStorageConnectionString = UseDevelopmentStorage=true
azureStorageConnectionEndpointSuffix = http://127.0.0.1:10000

Please advise

**Comment by emilkje** [comment]
I tried setting `useHttps: false` as well, to no avail. If it helps this is the parsed BlobStorageUri when running against the aforementioned configuration:
`{Primary = 'http://127.0.0.1:10000/devstoreaccount1'; Secondary = 'http://127.0.0.1:10000/devstoreaccount1-secondary'}`

**Comment by RaedJarrar** [comment]
remove: endpointSuffix: azureStorageConnectionEndpointSuffix from line 91 and try.

**Comment by emilkje** [comment]
Thanks for the reply. I did remove the suffix and got a bit further. The issue is where the Home Controller try to get the Organization name:

HomeController 
-> PortalBranding.RetrieveAsync() 
-> PortalBranding.GetPortalBrandingBlobAsync() 
-> AzureStorageService.GetPrivateCustomerPortalAssetsBlobContainerAzync()

When i hit the first line of `AzureStorageService.GetPrivateCustomerPortalAssetsBlobContainerAzync`  the `AzureStorageService.privateBlobContainer` is already instantiated with a uri that looks like this: `https://devstoreaccount1.blob.core.windows.net/customerportalassets` which obviously results in a 403 error when calling CreateIfNotExistsAsync at line 138.
