### ISSUE TITLE
Does this solution implement the secure application model framework?

### ISSUE THREAD

**Issue by knlp** [PartnerCenterSamples/Reseller-Web-Application#88]
Hi, Microsoft recently announced that partners must meet certain security requirements. One is MFA on all users and the other: "All partners integrating with a Microsoft API such as Azure Resource Manager, Microsoft Graph, and the Partner Center API must adopt the Secure Application Model framework to avoid any disruption to their integration when the baseline policies are enabled.", hence the question - does this solution implement the Secure Application Model framework?

**Comment by isaiahwilliams** [comment]
This project utilizes app only authentication when making calls to Microsoft Graph and the Partner Center API. Since app + user authentication is not used when interacting with the APIs, there is no code changes required.

**Comment by isaiahwilliams** [comment]
Please let us know if you have any concerns or questions.
